Avoid rewriting inherited field's annotations.
Using 'get_type_hints' for iteration here overwrite the inherited the default.

    pydantic_core._pydantic_core.ValidationError: 12 validation errors for FleetHealthOverviewTable
    title
      Field required [type=missing, input_value={'hx_name': 'FleetHealthO...ject at 0x7f3ef0c800b0>}, input_type=dict]
        For further information visit https://errors.pydantic.dev/2.6/v/missing
    active_row
      Field required [type=missing, input_value={'hx_name': 'FleetHealthO...ject at 0x7f3ef0c800b0>}, input_type=dict]
        For further information visit https://errors.pydantic.dev/2.6/v/missing
    active_filters
      Field required [type=missing, input_value={'hx_name': 'FleetHealthO...ject at 0x7f3ef0c800b0>}, input_type=dict]
        For further information visit https://errors.pydantic.dev/2.6/v/missing
    sort_column
      Field required [type=missing, input_value={'hx_name': 'FleetHealthO...ject at 0x7f3ef0c800b0>}, input_type=dict]
        For further information visit https://errors.pydantic.dev/2.6/v/missing
    sort_reverse
      Field required [type=missing, input_value={'hx_name': 'FleetHealthO...ject at 0x7f3ef0c800b0>}, input_type=dict]
        For further information visit https://errors.pydantic.dev/2.6/v/missing
    query
      Field required [type=missing, input_value={'hx_name': 'FleetHealthO...ject at 0x7f3ef0c800b0>}, input_type=dict]
        For further information visit https://errors.pydantic.dev/2.6/v/missing
    dynamic_filter_queries
      Field required [type=missing, input_value={'hx_name': 'FleetHealthO...ject at 0x7f3ef0c800b0>}, input_type=dict]
        For further information visit https://errors.pydantic.dev/2.6/v/missing
    dynamic_active_fitlers
      Field required [type=missing, input_value={'hx_name': 'FleetHealthO...ject at 0x7f3ef0c800b0>}, input_type=dict]
        For further information visit https://errors.pydantic.dev/2.6/v/missing
    pagination_disabled
      Field required [type=missing, input_value={'hx_name': 'FleetHealthO...ject at 0x7f3ef0c800b0>}, input_type=dict]
        For further information visit https://errors.pydantic.dev/2.6/v/missing
    page_max_items_choices
      Field required [type=missing, input_value={'hx_name': 'FleetHealthO...ject at 0x7f3ef0c800b0>}, input_type=dict]
        For further information visit https://errors.pydantic.dev/2.6/v/missing
    page_max_items
      Field required [type=missing, input_value={'hx_name': 'FleetHealthO...ject at 0x7f3ef0c800b0>}, input_type=dict]
        For further information visit https://errors.pydantic.dev/2.6/v/missing
    page_start
      Field required [type=missing, input_value={'hx_name': 'FleetHealthO...ject at 0x7f3ef0c800b0>}, input_type=dict]
        For further information visit https://errors.pydantic.dev/2.6/v/missing