Fix ValidationError in TodoList.toggle_all
When the toggle is off, is not sent from the client and the we fail with:

pydantic_core._pydantic_core.ValidationError: 1 validation error for toggle_all
toggle_all
  Missing required argument [type=missing_argument, input_value=ArgsKwargs((TodoList(id='...: 'all'>, query=None),)), input_type=ArgsKwargs]